project_id = "dukmdxpgibycgsvgqrbf"

[functions.criar-profissional]
verify_jwt = false

[functions.resetar-senha-profissional]
verify_jwt = false

[functions.sincronizar-realizado-trinks]
verify_jwt = false
