-- =====================================================
-- ACESSOS DO PAINEL
-- =====================================================
--
-- Para criar ou atualizar os usuarios reais no Supabase Auth, use:
--
-- $env:SUPABASE_URL="https://dukmdxpgibycgsvgqrbf.supabase.co"
-- $env:SUPABASE_SERVICE_ROLE_KEY="COLE_A_CHAVE_SERVICE_ROLE_AQUI"
-- npm run criar:acessos
--
-- A chave service_role fica em:
-- Supabase > Project Settings > API > service_role secret.
-- Nao coloque essa chave no GitHub nem no codigo do site.

-- | Perfil                            | Email              | Senha        |
-- |-----------------------------------|--------------------|--------------|
-- | Admin                             | admin@clinica.com  | Admin@2025!  |
-- | Erica Peres Ciriaco               | erica@clinica.com  | Erica@2025!  |
-- | Gilmara Sousa Cavalcante          | gilmara@clinica.com| Gilmara@2025!|
-- | Kelly Lavinya Silva Nascimento Sousa | kelly@clinica.com | Kelly@2025! |
-- | Maria Williara De Castro Silva    | maria@clinica.com  | Maria@2025!  |
-- | Tayane Borges De Sousa            | tayane@clinica.com | Tayane@2025! |

-- Este arquivo e apenas uma referencia dos acessos definidos.
-- O script scripts/criar-acessos-supabase.mjs cria os usuarios no Supabase Auth,
-- confirma os e-mails, define as senhas e sincroniza a tabela public.profiles.
