const MESES=["JANEIRO","FEVEREIRO","MARCO","ABRIL","MAIO","JUNHO","JULHO","AGOSTO","SETEMBRO","OUTUBRO","NOVEMBRO","DEZEMBRO"];
const LABEL=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"];
const META_ANUAL=187000;
const profissionais=[
{id:"kelly",nome:"Kelly Lavinya Silva Nascimento Sousa",nomeCurto:"Kelly",email:"kelly@clinica.com.br",perfil:"profissional"},
{id:"tayane",nome:"Tayane Borges de Sousa",nomeCurto:"Tayane",email:"tayane@clinica.com.br",perfil:"profissional"},
{id:"maria",nome:"Maria Williara de Castro Silva",nomeCurto:"Maria",email:"maria@clinica.com.br",perfil:"profissional"},
{id:"erica",nome:"Erica Peres Ciriaco",nomeCurto:"Erica",email:"erica@clinica.com.br",perfil:"profissional"},
{id:"gilmara",nome:"Gilmara Sousa Cavalcante",nomeCurto:"Gilmara",email:"gilmara@clinica.com.br",perfil:"profissional"},
{id:"admin",nome:"Dra. Roseane Debora",nomeCurto:"Roseane",email:"admin@clinica.com.br",perfil:"admin"}
];
let faturamento={kelly:[18415.6,23073.9,23781.5,33048.8,0,0,0,0,0,0,0,0],tayane:[15387.77,15648.1,18402.18,18824.2,0,0,0,0,0,0,0,0],maria:[6168,6488.89,3479.5,9509.2,0,0,0,0,0,0,0,0],erica:[1304,1240,180,2690.9,0,0,0,0,0,0,0,0],gilmara:[1400,415,120,1847,0,0,0,0,0,0,0,0]};
let avaliacoes={erica:{3:6138.9},gilmara:{3:7398}};
let metas=MESES.map((mes,i)=>i===1?{mes,mmmax:15900,mmmin:13250,mgm:45900,bonusBase:1350}:i>=10?{mes,mmmax:23000,mmmin:19166.67,mgm:70000,bonusBase:1350}:{mes,mmmax:18000,mmmin:15000,mgm:55000,bonusBase:1350});
const state={user:null,month:3,route:"painel",adminTab:"ranking"};
const $=s=>document.querySelector(s);const fmtBRL=v=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});const fmtPct=v=>`${v.toLocaleString("pt-BR",{maximumFractionDigits:1})}%`;const clamp=v=>Math.max(0,Math.min(100,v));
const profs=()=>profissionais.filter(p=>p.perfil==="profissional");const meta=()=>metas[state.month];const fat=(id,m=state.month)=>faturamento[id]?.[m]||0;const com=(id,m=state.month)=>Math.round(((avaliacoes[id]?.[m]||0)*.07)*100)/100;const totalClinica=(m=state.month)=>profs().reduce((s,p)=>s+fat(p.id,m),0);const anual=id=>faturamento[id].reduce((s,v)=>s+v,0);
function bonus(valor,m,total){const prop=Math.min(m.bonusBase,Math.round(m.bonusBase*(valor/m.mmmax)*100)/100);return valor>=m.mmmax||valor>=m.mmmin||total>=m.mgm?prop:0}
function status(valor,m){if(valor>=m.mmmax)return{label:"Acima da meta",gold:true};if(valor>=m.mmmin)return{label:"No gatilho",gold:true};return{label:"Abaixo do gatilho",gold:false}}
function rankingMensal(m=state.month){const mt=metas[m],tc=totalClinica(m);return profs().map(p=>{const f=fat(p.id,m),b=bonus(f,mt,tc),c=com(p.id,m);return{...p,fat:f,bonus:b,comissao:c,total:b+c,status:status(f,mt)}}).sort((a,b)=>b.fat-a.fat)}
function rankingAnual(){return profs().map(p=>({...p,acumulado:anual(p.id),pct:anual(p.id)/META_ANUAL*100})).sort((a,b)=>b.acumulado-a.acumulado)}
function init(){MESES.forEach((mes,i)=>{$("#monthSelect").insertAdjacentHTML("beforeend",`<option value="${i}" ${i===state.month?"selected":""}>${mes[0]+mes.slice(1).toLowerCase()} 2025</option>`)});$("#loginForm").addEventListener("submit",login);$("#logoutBtn").addEventListener("click",logout);$("#monthSelect").addEventListener("change",e=>{state.month=+e.target.value;render()})}
function login(e){e.preventDefault();const email=$("#email").value.trim().toLowerCase();const user=profissionais.find(p=>p.email===email);if(!user)return alert("E-mail nao encontrado nesta demo.");state.user=user;state.route=user.perfil==="admin"?"admin":"painel";$("#login").classList.add("is-hidden");$("#app").classList.remove("is-hidden");render()}
function logout(){state.user=null;$("#app").classList.add("is-hidden");$("#login").classList.remove("is-hidden")}
function menu(items){$("#navMenu").innerHTML=items.map(i=>`<button class="${i.active?"active":""}" data-route="${i.route}">${i.label}</button>`).join("");document.querySelectorAll("#navMenu button").forEach(b=>b.onclick=()=>{if(b.dataset.route==="logout")return logout();state.route=b.dataset.route;render()})}
function render(){const u=state.user;if(!u)return;$("#avatar").textContent=u.nomeCurto.slice(0,2).toUpperCase();$("#areaTitle").textContent=u.perfil==="admin"?"Painel administrativo":"Meu painel";if(u.perfil==="admin"){menu([{label:"Painel",route:"admin",active:state.route==="admin"},{label:"Faturamento",route:"faturamento",active:state.route==="faturamento"},{label:"Avaliacoes",route:"avaliacoes",active:state.route==="avaliacoes"},{label:"Metas",route:"metas",active:state.route==="metas"},{label:"WhatsApp",route:"whatsapp",active:state.route==="whatsapp"},{label:"Sair",route:"logout"}]);if(state.route==="faturamento")return telaFaturamento();if(state.route==="avaliacoes")return telaAvaliacoes();if(state.route==="metas")return telaMetas();if(state.route==="whatsapp")state.adminTab="whatsapp";return telaAdmin()}menu([{label:"Meu painel",route:"painel",active:true},{label:"Evolucao",route:"painel"},{label:"Ranking",route:"painel"},{label:"Sair",route:"logout"}]);telaProf(u)}
function kpi(label,value,detail,pct){return`<article class="card kpi-card"><div><div class="kpi-label">${label}</div><div class="kpi-value">${value}</div></div><div><div class="tiny">${detail}</div><div class="bar"><span style="--value:${clamp(pct)}%"></span></div></div></article>`}
function valores(mes,b,c){return`<section class="card gold-border"><h3>Valores a receber - ${mes.toLowerCase()} 2025</h3><div class="payment-row"><span>Bonus de meta</span><span class="money">${fmtBRL(b)}</span></div><div class="payment-row"><span>Comissao avaliacoes</span><span class="money">${fmtBRL(c)}</span></div><div class="payment-row payment-total"><strong>Total a receber</strong><span class="money">${fmtBRL(b+c)}</span></div></section>`}
function grafico(id){const max=Math.max(...faturamento[id],meta().mmmax);return`<section class="card"><h3>Evolucao mensal</h3><div class="chart">${faturamento[id].map((v,i)=>`<div class="chart-col"><div class="chart-bar"><span class="chart-fill" style="--height:${v?clamp(v/max*100):0}%"></span></div><div class="chart-label">${LABEL[i]}</div></div>`).join("")}</div><div class="tiny">Linhas tracejadas indicam gatilho e meta.</div></section>`}
function frase(pos){return["Voce lidera o ranking! Sua agenda e a chave para manter o bonus.","Vice-lideranca! Cada atendimento conta para chegar ao topo.","Top 3! Mantenha o ritmo e empurre sua agenda.","Voce esta a um passo do podio. Bora virar o jogo.","O mes ainda esta em curso. Vamos juntas!"][pos-1]||"Cada atendimento conta."}
function telaProf(u){const mt=meta(),f=fat(u.id),tc=totalClinica(),b=bonus(f,mt,tc),c=com(u.id),rank=rankingMensal().findIndex(p=>p.id===u.id)+1,rankA=rankingAnual().findIndex(p=>p.id===u.id)+1,acc=anual(u.id),st=status(f,mt);$("#content").innerHTML=`<section class="card welcome-card"><div><h2>Ola, ${u.nomeCurto}!</h2><div class="muted">Seu desempenho em ${mt.mes.toLowerCase()} 2025</div></div><span class="badge gold">${rank} lugar</span></section><section class="kpi-grid">${kpi("Meu realizado",fmtBRL(f),`${fmtPct(f/mt.mmmax*100)} da meta`,f/mt.mmmax*100)}${kpi("Meta do mes",fmtBRL(mt.mmmax),`Gatilho: ${fmtBRL(mt.mmmin)}`,mt.mmmin/mt.mmmax*100)}${kpi("% atingido",fmtPct(f/mt.mmmax*100),`<span class="badge ${st.gold?"gold":""}">${st.label}</span>`,f/mt.mmmax*100)}${kpi("Meta anual","R$ 187k",`${fmtPct(acc/META_ANUAL*100)} atingido`,acc/META_ANUAL*100)}</section>${valores(mt.mes,b,c)}${grafico(u.id)}<section class="card gold-border"><div class="section-head"><div><h3>Meta anual: ${fmtBRL(META_ANUAL)}</h3><div class="muted">Acumulado: ${fmtBRL(acc)} · Falta: ${fmtBRL(Math.max(0,META_ANUAL-acc))}</div></div><span class="money">${fmtPct(acc/META_ANUAL*100)}</span></div><div class="bar" style="margin-top:12px"><span style="--value:${clamp(acc/META_ANUAL*100)}%"></span></div></section><section class="card ranking-card"><div class="section-head"><h3>Minha posicao no ranking</h3><span class="badge gold">Mensal: ${rank} · Anual: ${rankA}</span></div><p class="muted">${frase(rank)}</p></section>`}
function telaAdmin(){const mt=meta(),total=totalClinica(),rk=rankingMensal(),totCom=rk.reduce((s,r)=>s+r.comissao,0),ticket=total/Math.max(1,rk.filter(r=>r.fat>0).length);$("#content").innerHTML=`<section class="admin-kpi-grid card">${kpi("Faturamento total",fmtBRL(total),"Realizado no mes",total/mt.mgm*100)}${kpi("Meta clinica",fmtBRL(mt.mgm),"MGM",100)}${kpi("Falta para meta",fmtBRL(Math.max(0,mt.mgm-total)),"Saldo geral",total/mt.mgm*100)}${kpi("% atingimento",fmtPct(total/mt.mgm*100),"Clinica",total/mt.mgm*100)}${kpi("Gatilho",fmtBRL(mt.mmmin),"MMmin",mt.mmmin/mt.mmmax*100)}${kpi("Meta mes",fmtBRL(mt.mmmax),"MMmax",100)}${kpi("Ticket medio",fmtBRL(ticket),"Por profissional",75)}${kpi("Total comissoes",fmtBRL(totCom),"Avaliacoes",100)}</section><section class="tab-row"><button data-tab="ranking" class="${state.adminTab==="ranking"?"active":""}">Ranking mensal</button><button data-tab="bonus" class="${state.adminTab==="bonus"?"active":""}">Bonus e comissoes</button><button data-tab="anual" class="${state.adminTab==="anual"?"active":""}">Ranking anual</button><button data-tab="whatsapp" class="${state.adminTab==="whatsapp"?"active":""}">WhatsApp</button></section><section>${adminTab()}</section>`;document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{state.adminTab=b.dataset.tab;telaAdmin()})}
function adminTab(){if(state.adminTab==="bonus")return tabelaBonus();if(state.adminTab==="anual")return tabelaAnual();if(state.adminTab==="whatsapp")return whats();return tabelaRanking()}
function tabelaRanking(){return`<section class="card table-wrap"><table><thead><tr><th>Pos.</th><th>Profissional</th><th>Realizado</th><th>% Meta</th><th>Status</th><th>Bonus</th></tr></thead><tbody>${rankingMensal().map((r,i)=>`<tr><td>${i+1}</td><td>${r.nomeCurto}</td><td class="money">${fmtBRL(r.fat)}</td><td>${fmtPct(r.fat/meta().mmmax*100)}</td><td><span class="badge ${r.status.gold?"gold":""}">${r.status.label}</span></td><td>${fmtBRL(r.bonus)}</td></tr>`).join("")}</tbody></table></section>`}
function tabelaBonus(){const rows=rankingMensal(),total=rows.reduce((s,r)=>s+r.total,0);return`<section class="card table-wrap"><table><thead><tr><th>Pos.</th><th>Profissional</th><th>Realizado</th><th>Bonus</th><th>Comissao 7%</th><th>Total</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${r.nomeCurto}</td><td>${fmtBRL(r.fat)}</td><td>${fmtBRL(r.bonus)}</td><td class="money">${fmtBRL(r.comissao)}</td><td class="money">${fmtBRL(r.total)}</td></tr>`).join("")}<tr><td colspan="5"><strong>Total geral</strong></td><td class="money">${fmtBRL(total)}</td></tr></tbody></table></section>`}
function tabelaAnual(){return`<section class="card table-wrap"><table><thead><tr><th>Profissional</th><th>Acumulado</th><th>% meta</th><th>Falta</th><th>Progresso</th></tr></thead><tbody>${rankingAnual().map(r=>`<tr><td>${r.nomeCurto}</td><td class="money">${fmtBRL(r.acumulado)}</td><td>${fmtPct(r.pct)}</td><td>${fmtBRL(Math.max(0,META_ANUAL-r.acumulado))}</td><td><div class="bar"><span style="--value:${clamp(r.pct)}%"></span></div></td></tr>`).join("")}</tbody></table></section>`}
function whats(){const msg=gerarWhatsapp();setTimeout(()=>{$("#copyWhats").onclick=()=>navigator.clipboard.writeText(msg).then(()=>$("#copyWhats").textContent="Copiado")},0);return`<section class="card"><div class="section-head"><h3>Mensagem WhatsApp</h3><button id="copyWhats" class="copy-button">Copiar mensagem</button></div><div class="whatsapp-preview"><div class="whatsapp-bubble">${msg.replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}</div></div></section>`}
function gerarWhatsapp(){const mt=meta(),rows=rankingMensal(),ano=rankingAnual();let l=[`PAINEL DE RESULTADOS - ${mt.mes}`,"Centro Estetico Dra. Roseane Debora",`Realizado no mes: ${fmtBRL(totalClinica())}`,`Bonus base do mes: ${fmtBRL(mt.bonusBase)}`,`Saldo p/ meta geral: ${fmtBRL(Math.max(0,mt.mgm-totalClinica()))}`,"","RANKING MENSAL",""];rows.forEach((r,i)=>{l.push(`${i+1}. ${r.nome}`,`${fmtBRL(r.fat)} · ${fmtPct(r.fat/mt.mmmax*100)} da meta`,`Saldo p/ meta mensal: ${fmtBRL(Math.max(0,mt.mmmax-r.fat))} · ${r.status.label}`,`Bonus: ${fmtBRL(r.bonus)} | Comissao: ${fmtBRL(r.comissao)} | Total: ${fmtBRL(r.total)}`,frase(i+1),"")});l.push("RANKING ANUAL","");ano.forEach((r,i)=>l.push(`${i+1}. ${r.nomeCurto}`,`Acumulado: ${fmtBRL(r.acumulado)} · Falta: ${fmtBRL(Math.max(0,META_ANUAL-r.acumulado))}`,""));l.push("Bora bater as metas!");return l.join("\n")}
function telaFaturamento(){const rows=profs().map(p=>`<tr><td>${p.nomeCurto}</td><td><input data-fat="${p.id}" value="${fat(p.id).toFixed(2)}"></td><td>${fmtBRL(fat(p.id))}</td></tr>`).join("");$("#content").innerHTML=`<section class="card"><h2>Lancamento de faturamento</h2><p class="muted">Edite o valor total do mes selecionado.</p></section><section class="card table-wrap editable-table"><table><tbody>${rows}</tbody></table></section>`;document.querySelectorAll("[data-fat]").forEach(i=>i.onchange=()=>{faturamento[i.dataset.fat][state.month]=Number(i.value.replace(",","."))||0;telaFaturamento()})}
function telaAvaliacoes(){const rows=profs().map(p=>{const v=avaliacoes[p.id]?.[state.month]||0;return`<tr><td>${p.nomeCurto}</td><td><input data-avaliacao="${p.id}" value="${v.toFixed(2)}"></td><td class="money">${fmtBRL(v*.07)}</td></tr>`}).join("");$("#content").innerHTML=`<section class="card"><h2>Lancamento de avaliacoes</h2><p class="muted">Comissao calculada em 7%.</p></section><section class="card table-wrap editable-table"><table><tbody>${rows}</tbody></table></section>`;document.querySelectorAll("[data-avaliacao]").forEach(i=>i.onchange=()=>{avaliacoes[i.dataset.avaliacao]=avaliacoes[i.dataset.avaliacao]||{};avaliacoes[i.dataset.avaliacao][state.month]=Number(i.value.replace(",","."))||0;telaAvaliacoes()})}
function telaMetas(){const rows=metas.map((m,i)=>`<tr><td>${m.mes}</td><td><input data-meta="${i}:mmmax" value="${m.mmmax}"></td><td><input data-meta="${i}:mmmin" value="${m.mmmin}"></td><td><input data-meta="${i}:mgm" value="${m.mgm}"></td></tr>`).join("");$("#content").innerHTML=`<section class="card"><h2>Metas mensais</h2></section><section class="card table-wrap editable-table"><table><tbody>${rows}</tbody></table></section>`;document.querySelectorAll("[data-meta]").forEach(i=>i.onchange=()=>{const[a,f]=i.dataset.meta.split(":");metas[a][f]=Number(i.value.replace(",","."))||0;telaMetas()})}
init();
